title: "MSc. Felipe S. Manzoni"
description: "Call me Manzoni, MSc. in Computer Science, Ph.D. candidate in SE for AI/ML and Data Science."
desc_projects: "I'm currently a Ph.D. candidate in SE4AI and AI4SE, also I interrest myself in testing, usability and other research topics."
url: "https://felpsmanzoni.github.io"
baseurl: ""

theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
markdown: kramdown

logo: assets/images/Professional_Perfil_Close.jpg
show_downloads: false

# NAV BAR items configuration:
nav:
  - { title: Home, url: / }
  - { title: About, url: /about/ }
  - { title: Blog, url: /blog/ }
  - { title: CV, url: /cv/ }
  - { title: Projects, url: /projects/ }
#  - { title: Contact, url: /contact/ }
